name: Build Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: wiiuenv/devkitppc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install WUPS
        run: |
          # Hier wird das fehlende Werkzeug installiert
          apk update
          apk add wups-dev
      - name: Build
        run: make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: King-Gamepad-Plugin
          path: "*.wps"
