name: Build King Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: wiiuenv/devkitppc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install WUPS
        run: dkp-pacman -Syu --noconfirm wups-dev wut
      - name: Build
        run: |
          make clean
          make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: King-Gamepad-vWii
          path: "*.wps"
