name: Build Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: wiiuenv/devkitppc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install WUPS Dev
        run: apk add wups-dev
      - name: Build
        run: make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: King-Plugin-Download
          path: "*.wps"
