name: Build Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: wiiuenv/devkitppc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install WUPS
        run: |
          # Wir nutzen jetzt den richtigen Befehl f√ºr diesen Server
          apt-get update
          apt-get install -y wups-dev
      - name: Build
        run: make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: King-Gamepad-vWii-Plugin
          path: "*.wps"
